apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dags
  labels:
    app: airflow-dags
spec:
  storageClassName: manual

  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: airflow-dags
    namespace: airflow
  hostPath:
    path: /tmp/data/